# go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y

# 啟用平滑游標移動與加速曲線
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# 初始移動速度（精準定位用）
CONFIG_ZMK_POINTING_DEFAULT_MOVE_TIME_TO_MAX=300
CONFIG_ZMK_POINTING_DEFAULT_MOVE_ACCELERATION_EXPONENT=2
